---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-slim

inputs:
- name: src
- name: src-ci

outputs:
- name: build
- name: version

run:
  path: src-ci/ci/tasks/maven-package/maven-package.sh