---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: spotter-src
  type: pull-request
  source:
    repository: ((github.repository))
    access_token: ((github.access-token))
    
- name: docker-image-spotter
  type: docker-image
  source:
    repository: ((docker.registry.repository))
    username: ((docker.registry.username))
    password: ((docker.registry.password))
    
jobs:           
- name: Build Spotter
  plan:
  - get: spotter-src
    trigger: true
    version: every
  - task: "Build Spotter with Maven"
    file: src-ci/ci/tasks/maven-package/maven-package.yml
    input_mapping:
      src: spotter-src
      src-ci: src-ci
  - put: docker-image-spotter
    params:
      build: build